
package main;
import dto.DTOArticulo;
import dto.DTOProveedor;
import dto.DTOTipoArticulo;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static org.hibernate.jpa.criteria.ValueHandlerFactory.isNumeric;
/**
 *
 * @author TroikaP
 */
public class InterfazArticulo extends javax.swing.JFrame {

    /**
     * Creates new form InterfazArticulo
     */
    private ControladorDistribucionPapelFilm controlador;
    private InterfazABMArticulo pantallaSecundaria;
    private boolean Agregar;
    public InterfazArticulo() {
        initComponents();
    }
    public InterfazArticulo(ControladorDistribucionPapelFilm controlador, InterfazABMArticulo interfaz) {
        initComponents();
        //this.Agregar = false;
        this.controlador = controlador;
        this.pantallaSecundaria = interfaz;
        this.Agregar = true;
    }
    public InterfazArticulo(ControladorDistribucionPapelFilm controlador, InterfazABMArticulo interfaz, DTOArticulo dto) {
        initComponents();
        //this.Agregar = false;
        this.controlador = controlador;
        this.pantallaSecundaria = interfaz;
        this.Agregar = false;
        this.TextoCodigo.disable();
        TextoCodigo.setText(String.valueOf(dto.getCodigoDTOArticulo()));
        TextoNombre.setText(dto.getNombreDTOArticulo());
        TextoDescripcion.setText(dto.getDescripcionDTOArticulo());
        TextoTipoArticulo.setText(dto.getDtoTipoArticuloDTOArticulo().getNombreDTOTipoArticulo());
        TextoCodigoTipoArticulo.setText(String.valueOf(dto.getDtoTipoArticuloDTOArticulo().getCodigoDTOTipoArticulo()));
        TextoProveedor.setText(dto.getDtoProveedorDTOArticulo().getNombreDTOProveedor());
        TextoCodigoProveedor.setText(String.valueOf(dto.getDtoProveedorDTOArticulo().getCodigoDTOProveedor()));
    }
    public void ConfirmarProveedor(DTOProveedor dto)
    {
        TextoProveedor.setText(dto.getNombreDTOProveedor());
        TextoCodigoProveedor.setText(String.valueOf(dto.getCodigoDTOProveedor()));
    }
    public void ConfirmarTipoArticulo(DTOTipoArticulo dto)
    {
        TextoTipoArticulo.setText(dto.getNombreDTOTipoArticulo());
        TextoCodigoTipoArticulo.setText(String.valueOf(dto.getCodigoDTOTipoArticulo()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        TextoCodigo = new javax.swing.JTextField();
        TextoNombre = new javax.swing.JTextField();
        TextoDescripcion = new javax.swing.JTextField();
        Codigo = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Descripcion = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Aceptar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        TipoArticulo = new javax.swing.JLabel();
        Proveedor = new javax.swing.JLabel();
        TextoTipoArticulo = new javax.swing.JTextField();
        TextoProveedor = new javax.swing.JTextField();
        CambiarTipoArticulo = new javax.swing.JButton();
        CambiarProveedor = new javax.swing.JButton();
        TextoCodigoTipoArticulo = new javax.swing.JTextField();
        TextoCodigoProveedor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setTitle("Articulo");
        jInternalFrame1.setVisible(true);

        TextoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoCodigoActionPerformed(evt);
            }
        });

        Codigo.setText("Codigo");

        Nombre.setText("Nombre");

        Descripcion.setText("Descripcion");

        jLabel5.setText("Sobre el Articulo");

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        TipoArticulo.setText("TipoArticulo");

        Proveedor.setText("Proveedor");

        CambiarTipoArticulo.setText("CambiarTipoArticulo");
        CambiarTipoArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambiarTipoArticuloActionPerformed(evt);
            }
        });

        CambiarProveedor.setText("CambiarProveedor");
        CambiarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambiarProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Codigo)
                                .addComponent(Nombre)
                                .addComponent(TipoArticulo)
                                .addComponent(Proveedor)
                                .addComponent(Descripcion, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TextoCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                .addComponent(TextoNombre)
                                .addComponent(TextoDescripcion))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TextoProveedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                    .addComponent(TextoTipoArticulo, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextoCodigoTipoArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextoCodigoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(4, 4, 4)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CambiarTipoArticulo)
                            .addComponent(CambiarProveedor)))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(Aceptar)
                        .addGap(86, 86, 86)
                        .addComponent(Cancelar)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Codigo))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nombre))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Descripcion))
                        .addGap(20, 20, 20)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextoTipoArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoCodigoTipoArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoCodigoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(147, 147, 147)
                        .addComponent(TipoArticulo)
                        .addGap(26, 26, 26)
                        .addComponent(Proveedor))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(CambiarTipoArticulo)
                        .addGap(17, 17, 17)
                        .addComponent(CambiarProveedor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancelar)
                    .addComponent(Aceptar))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoCodigoActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
        if (TextoCodigo.getText()!=null && !TextoCodigo.getText().trim().isEmpty() && TextoNombre.getText()!=null && !TextoNombre.getText().trim().isEmpty() && TextoDescripcion.getText()!=null && !TextoDescripcion.getText().trim().isEmpty())
        {
            DTOArticulo dtoNuevo = new DTOArticulo();
            dtoNuevo.setCodigoDTOArticulo(Integer.parseInt(TextoCodigo.getText()));
            dtoNuevo.setNombreDTOArticulo(TextoNombre.getText());
            dtoNuevo.setDescripcionDTOArticulo(TextoDescripcion.getText());
            if(TextoCodigoTipoArticulo.getText()!=null && !TextoCodigoTipoArticulo.getText().trim().isEmpty())
            {
                DTOTipoArticulo dto = new DTOTipoArticulo();
                dto.setCodigoDTOTipoArticulo(Integer.valueOf(TextoCodigoTipoArticulo.getText()));
                dtoNuevo.setDtoTipoArticuloDTOArticulo(dto);
            }
            if(TextoCodigoProveedor.getText()!=null && !TextoCodigoProveedor.getText().trim().isEmpty())
            {
                DTOProveedor dto = new DTOProveedor();
                dto.setCodigoDTOProveedor(Integer.valueOf(TextoCodigoProveedor.getText()));
                dtoNuevo.setDtoProveedorDTOArticulo(dto);
            }
            controlador.GuardarArticulo(dtoNuevo, this.Agregar);
            this.dispose();
            InterfazABMArticulo newInterfaz = new InterfazABMArticulo(controlador,null);
            newInterfaz.setVisible(true);
        }
        else{ JOptionPane.showMessageDialog(null, "Esta vacio algun campo.");
        }
    }//GEN-LAST:event_AceptarActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
        //this.setVisible(false);
        this.dispose();
        pantallaSecundaria.setVisible(true);
    }//GEN-LAST:event_CancelarActionPerformed

    private void CambiarTipoArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambiarTipoArticuloActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CambiarTipoArticuloActionPerformed

    private void CambiarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambiarProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CambiarProveedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazArticulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton CambiarProveedor;
    private javax.swing.JButton CambiarTipoArticulo;
    private javax.swing.JButton Cancelar;
    private javax.swing.JLabel Codigo;
    private javax.swing.JLabel Descripcion;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Proveedor;
    private javax.swing.JTextField TextoCodigo;
    private javax.swing.JTextField TextoCodigoProveedor;
    private javax.swing.JTextField TextoCodigoTipoArticulo;
    private javax.swing.JTextField TextoDescripcion;
    private javax.swing.JTextField TextoNombre;
    private javax.swing.JTextField TextoProveedor;
    private javax.swing.JTextField TextoTipoArticulo;
    private javax.swing.JLabel TipoArticulo;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
